'use client';
/* eslint-disable @next/next/no-img-element */
import { useCallback, useEffect, useRef, useState } from 'react';
import { ArrowLeft, ArrowUpRight, Copy, HelpCircle, RotateCcw, Sparkles, X, Users, ShieldCheck, Eye, Check } from 'lucide-react';
import catalog from '../../game/cards.json';
import rules from '../../game/rules.json';
import type { Card, Command, Move, view } from '../../game/online';
import './play.css';
type Table=ReturnType<typeof view>&{code:string};
const def=(key:string)=>catalog.cards.find(c=>c.key===key)!;
function CardFace({card,onClick,small=false}:{card:Card|string;onClick?:()=>void;small?:boolean}){const key=typeof card==='string'?card:card.key;return <button className={`pdf-card ${small?'small':''}`} onClick={onClick} aria-label={`Inspect ${def(key)?.name||'card back'}`} type="button"><img draggable={false} src={`/cards/${key}.png`} alt={def(key)?`${def(key).name}. ${def(key).effect}`:'UNICORN card back'}/></button>;}
export default function OnlineTrial(){
 const [table,setTable]=useState<Table|null>(null),[room,setRoom]=useState(''),[name,setName]=useState(''),[joinCode,setJoinCode]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[needsJoin,setNeedsJoin]=useState(false),[loading,setLoading]=useState(false),[inspect,setInspect]=useState<Card|string|null>(null),[showRules,setShowRules]=useState(false),[copied,setCopied]=useState(false),[connected,setConnected]=useState(true);
 const current=useRef<Table|null>(null),requesting=useRef(false);
 const accept=useCallback((data:Table)=>{if(!current.current||data.code!==current.current.code||data.revision>=current.current.revision){current.current=data;setTable(data);}setNeedsJoin(false);setConnected(true);},[]);
 const refresh=useCallback(async(code:string)=>{try{const r=await fetch(`/api/game/${code}`,{cache:'no-store'});const data=await r.json();if(r.ok)accept(data);else if(data.needsJoin){setNeedsJoin(true);setTable(null);current.current=null;}else {setError(data.error);setConnected(false);}}catch{setConnected(false);}finally{setLoading(false);}},[accept]);
 useEffect(()=>{const code=new URLSearchParams(window.location.search).get('room')?.toUpperCase()||'';if(code){setRoom(code);setJoinCode(code);setLoading(true);void refresh(code);}},[refresh]);
 useEffect(()=>{if(!room||needsJoin)return;const tick=setInterval(()=>{if(!requesting.current&&document.visibilityState==='visible')void refresh(room);},1500);const onVisible=()=>{if(document.visibilityState==='visible')void refresh(room);};document.addEventListener('visibilitychange',onVisible);return()=>{clearInterval(tick);document.removeEventListener('visibilitychange',onVisible);};},[room,needsJoin,refresh]);
 async function send(url:string,payload:unknown){if(requesting.current)return;requesting.current=true;setBusy(true);setError('');try{const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await r.json();if(!r.ok){setError(data.error||'Could not apply that move.');if(r.status===409&&room)await refresh(room);return;}accept(data);setRoom(data.code);setJoinCode(data.code);window.history.replaceState(null,'',`/play?room=${data.code}`);setInspect(null);}catch{setError('Connection interrupted. Refresh the table before trying again.');setConnected(false);}finally{requesting.current=false;setBusy(false);}}
 const move=(command:Command)=>table&&send(`/api/game/${table.code}`,{revision:table.revision,command});
 const person=(id:unknown)=>table?.players.find(p=>p.id===id)?.name||'Player';
 const me=table?.players.find(p=>p.id===table.you),myTurn=table?.turn===table?.you;
 const pending=table?.pending;const waiting=Array.isArray(pending?.waiting)?pending.waiting as string[]:[];
 const inspectedKey=typeof inspect==='string'?inspect:inspect?.key;
 const selectedMoves=table?.moves.filter(m=>typeof inspect==='object'&&inspect&&m.command.cardId===inspect.id)||[];
 const shownMoves=(table?.moves||[]).filter(m=>!['bank','effect'].includes(m.command.type));
 let status='';if(table){if(table.phase==='lobby')status=`${table.players.length} of 5 seats filled. Invite at least 3 players to start.`;else if(table.phase==='setup')status=table.choices.length?'Choose one of your three startups.':`${table.players.find(p=>!p.startup)?.name||'A player'} is choosing a startup.`;else if(table.phase==='finished')status=`${person(table.winner)} is the Unicorn!`;else if(table.overflow.length)status=table.overflow.map(p=>`${person(p.id)} must discard ${p.count}`).join(' · ');else if(pending)status=pending.kind==='venture'?`${person(pending.actor)} invited ${person(pending.target)} to partner.`:pending.kind==='mixer'?'Founder Mixer: choose secretly, then everyone passes left.':pending.kind==='reveal'?`${person(pending.actor)} is privately viewing ${person(pending.target)}’s hand.`:pending.kind==='offer'?`${person(pending.actor)} may counter Golden Handcuffs.`:`${person(pending.actor)} played ${(pending.card as Card)?.key?def((pending.card as Card).key).name:'an attack'} against ${person(pending.target)}.`;else status=myTurn?(table.step==='draw'?'Your turn. Draw one card.':`Your turn. ${table.plays} card ${table.plays===1?'play':'plays'} left.`):`${person(table.turn)}’s turn.`;}
 async function copy(){try{await navigator.clipboard.writeText(`${window.location.origin}/play?room=${room}`);setCopied(true);setTimeout(()=>setCopied(false),2500);}catch{setError('Copy the room link from your browser address bar.');}}
 return <main className="online-app"><header className="online-header"><a className="online-logo" href="/"><Sparkles/>UNICORN</a><span className="online-tag">ONLINE TRIAL</span><div className="online-header-actions"><button onClick={()=>setShowRules(true)}><HelpCircle size={18}/> Rules & cards</button><a href="/"><ArrowLeft size={16}/> Back to website</a></div></header>
 {!table?<section className="online-welcome"><div className="welcome-copy"><span className="online-eyebrow">SAME CARDS. REAL FRIENDS.</span><h1>WELCOME TO<br/>THE <em>TABLE.</em></h1><p>Build a startup. Partner up. Betray them.<br/>First to $1B wins.</p><div className="online-pills"><span>3–5 players</span><span>100-card deck</span><span>~45 minutes</span></div><div className="welcome-deck"><img src="/cards/back.png" alt="Original UNICORN card back"/><img src="/cards/ditch.png" alt="Ditch, using the original PDF design"/><img src="/cards/chief-scientist.png" alt="Chief Scientist, using the original PDF design"/></div></div><div className="lobby-panel"><h2>{needsJoin?'Your seat is waiting.':'Bring your friends.'}</h2><p>Everyone plays on their own device. Your hand stays private.</p><label htmlFor="player-name">Your name</label><input id="player-name" autoComplete="nickname" maxLength={24} placeholder="What should we call you?" value={name} onChange={e=>setName(e.target.value)}/><button className="online-primary" disabled={busy||!name.trim()||loading} onClick={()=>send('/api/game',{name})}>Create a room <ArrowUpRight size={19}/></button><div className="lobby-divider">OR JOIN YOUR FRIENDS</div><label htmlFor="room-code">Room code</label><input id="room-code" className="room-input" maxLength={8} autoCapitalize="characters" placeholder="8-character code" value={joinCode} onChange={e=>setJoinCode(e.target.value.toUpperCase().replace(/[^A-Z2-9]/g,''))}/><button className="online-secondary" disabled={busy||!name.trim()||joinCode.length!==8||loading} onClick={()=>send(`/api/game/${joinCode}`,{type:'join',name})}>Join room <Users size={18}/></button>{loading&&<p role="status">Reconnecting to your table…</p>}{error&&<p className="online-error" role="alert">{error}</p>}<p className="lobby-note">Free trial · No account needed to play</p></div></section>:<>
 <section className="room-bar"><div><span className="online-eyebrow">YOUR TABLE</span><button className="room-code" onClick={copy}>{table.code} {copied?<Check size={20}/>:<Copy size={20}/>}</button></div><p>You’re <strong>{me?.name}</strong> <span className={connected?'online-connected':'online-disconnected'}>{connected?'● Connected':'● Reconnecting'}</span></p><button className="online-secondary" onClick={copy}>{copied?'Link copied':'Invite friends'}<Copy size={16}/></button></section>
 {error&&<div className="online-error" role="alert">{error}<button onClick={()=>refresh(room)}>Refresh table</button></div>}
 <section className={`turn-banner ${myTurn?'your-turn':''}`} aria-live="polite"><div><span className="online-eyebrow">{table.phase==='finished'?'ONE BILLION. ONE WINNER.':pending?'TABLE MOMENT':table.phase==='lobby'?'GET EVERYONE IN':'THE NEXT MOVE'}</span><h2>{status}</h2>{pending&&waiting.length>0&&<p>Waiting for {waiting.map(person).join(' and ')}.</p>}</div><div className="turn-controls">{shownMoves.filter(m=>!['choose','mix','discard','react','accept'].includes(m.command.type)).map((m,i)=><button key={i} disabled={busy} className="online-primary" onClick={()=>move(m.command)}>{m.label}{m.command.type==='start'?<ArrowUpRight size={18}/>:null}</button>)}</div></section>
 {table.phase==='lobby'?<section className="lobby-seats">{Array.from({length:5},(_,i)=>{const p=table.players[i];return <div className={`seat ${p?'occupied':''}`} key={i}><div className="seat-number">0{i+1}</div><h3>{p?.name||'Seat available'}</h3><span>{p?(p.id===table.host?'Host':'Ready to play'):'Share the room link'}</span></div>;})}<p>Each player gets five hidden cards and chooses one of three startups. Nothing special is guaranteed.</p></section>:<>
 {table.choices.length>0&&<section className="startup-choices">{table.choices.map(key=><div key={key}><CardFace card={key} onClick={()=>setInspect(key)}/><button disabled={busy} className="online-primary" onClick={()=>move({type:'choose',key})}>Choose {def(key).name}</button></div>)}</section>}
 <section className="players-grid">{table.players.map(p=><article className={`startup-panel ${p.id===table.you?'is-you':''} ${p.id===table.turn?'is-active':''}`} key={p.id}><div className="player-heading"><div><span className="online-eyebrow">{p.name}{p.id===table.you?' · YOU':''}</span><h3>{p.startup?def(p.startup).name:'Choosing a startup'}</h3></div><strong className="player-value">${p.valuation}<small>M</small></strong></div><div className="valuation-track"><span style={{width:`${Math.min(100,p.valuation/10)}%`}}/></div><div className="player-meta"><span>{p.handCount} hidden cards</span>{p.partner&&<span>Partner: {person(p.partner)}</span>}</div><div className="startup-cards">{p.startup&&<CardFace card={p.startup} small onClick={()=>setInspect(p.startup!)}/>} {p.bank.map(c=><div className="asset-slot" key={c.id}><CardFace card={c} small onClick={()=>setInspect(c)}/>{c.attachments?.map(a=><button className="attachment-chip" key={a.id} onClick={()=>setInspect(a)}><ShieldCheck size={12}/>Non-Compete</button>)}</div>)}</div>{!p.bank.length&&<p className="empty-bank">Your startup assets go here.</p>}{p.effects.length>0&&<div className="active-effects"><span>ACTIVE EFFECTS · no bank value</span>{p.effects.map(c=><button key={c.id} onClick={()=>setInspect(c)}>{def(c.key).name} {c.key==='pr-crisis'?'−$75M':'Skip next turn'}</button>)}</div>}</article>)}</section>
 {table.ventures.map(v=><section className="venture-table" key={v.card.id}><div><span className="online-eyebrow">JOINT VENTURE</span><h3>{v.members.map(m=>person(m.owner)).join(' + ')}</h3><p>Both count both Employees. Trust is temporary.</p><button onClick={()=>setInspect(v.card)}>Inspect Joint Venture</button></div><div className="shared-employees">{v.members.map(m=><div key={m.card.id}><CardFace card={m.card} onClick={()=>setInspect(m.card)}/><span>Contributed by {person(m.owner)}</span>{m.card.attachments?.map(a=><button className="attachment-chip" key={a.id} onClick={()=>setInspect(a)}>Protected by Non-Compete</button>)}</div>)}</div></section>)}
 {shownMoves.some(m=>['react','accept','mix','discard'].includes(m.command.type))&&<section className="response-panel"><h3>{table.overflow.some(p=>p.id===table.you)?'Discard down to seven':pending?.kind==='venture'?'Choose the Employee you’ll share':pending?.kind==='mixer'?'Choose one card to pass left':'Your reaction'}</h3><div>{shownMoves.filter(m=>['react','accept','mix','discard'].includes(m.command.type)).map((m,i)=><button className="online-secondary" key={i} disabled={busy} onClick={()=>move(m.command)}>{m.label}</button>)}</div></section>}
 <section className="hand-panel"><div className="hand-heading"><div><span className="online-eyebrow"><Eye size={13}/> ONLY YOU CAN SEE THESE</span><h2>Your hand <span>{table.hand.length}/7</span></h2></div><p>Click a card to read it, use its effect, or bank it.</p><span className="deck-count">{table.deckCount} in draw pile</span></div><div className="hand-cards">{table.hand.map(c=><CardFace key={c.id} card={c} onClick={()=>setInspect(c)}/>)}</div>{!table.hand.length&&<p className="empty-hand">Your hand is empty. Draw at the start of your next turn.</p>}</section>
 <section className="table-bottom"><details><summary>Table history</summary><ol>{table.log.slice().reverse().map((l,i)=><li key={i}>{l}</li>)}</ol></details><details><summary>Discard pile · {table.discard.length} cards</summary><div className="discard-cards">{table.discard.slice().reverse().map(c=><CardFace key={c.id} small card={c} onClick={()=>setInspect(c)}/>)}</div></details></section></>}
 </>}
 {inspect&&inspectedKey&&<div className="online-modal-shade" onClick={()=>setInspect(null)}><section className="online-modal card-modal" role="dialog" aria-modal="true" aria-label={def(inspectedKey).name} onClick={e=>e.stopPropagation()}><button className="modal-close" autoFocus aria-label="Close card" onClick={()=>setInspect(null)}><X/></button><img className="full-card" src={`/cards/${inspectedKey}.png`} alt={`${def(inspectedKey).name}: ${def(inspectedKey).effect}`}/><div className="card-options"><span className="online-eyebrow">ORIGINAL PRINTED CARD</span><h2>{def(inspectedKey).name}</h2>{selectedMoves.length?<><p>Choose one use. Banking a card makes its effect unavailable.</p>{selectedMoves.map((m:Move,i:number)=><button className={m.command.type==='bank'?'online-secondary':'online-primary'} key={i} disabled={busy} onClick={()=>move(m.command)}>{m.label}</button>)}</>:<p>{table?.hand.some(c=>typeof inspect==='object'&&c.id===inspect.id)?'No play is available for this card right now. You can keep it for a later turn or reaction.':def(inspectedKey).effect}</p>}<button className="online-text-button" onClick={()=>setInspect(null)}>Back to the table</button></div></section></div>}
 {table?.reveal&&<div className="online-modal-shade"><section className="online-modal reveal-modal" role="dialog" aria-modal="true" aria-label="Private Founder Scandal reveal"><span className="online-eyebrow">FOUNDER SCANDAL · ONLY YOU SEE THIS</span><h2>{person(pending?.target)}’s hand</h2><div>{table.reveal.map(c=><img key={c.id} src={`/cards/${c.key}.png`} alt={`${def(c.key).name}: ${def(c.key).effect}`}/>)}</div><button className="online-primary" disabled={busy} onClick={()=>move({type:'ack'})}>Done viewing</button></section></div>}
 {showRules&&<div className="online-modal-shade" onClick={()=>setShowRules(false)}><section className="online-modal rules-modal" role="dialog" aria-modal="true" aria-label="Printed game rules" onClick={e=>e.stopPropagation()}><button className="modal-close" autoFocus aria-label="Close rules" onClick={()=>setShowRules(false)}><X/></button><span className="online-eyebrow">THE SAME PRINTED GAME</span><h2>One billion. One winner.</h2><p>100 draw cards · 15 startup cards · 5 reference cards. The online table pauses for eligible players to defend or pass.</p><a href="/downloads/UNICORN-printable-deck.pdf" target="_blank" rel="noreferrer">Open the original PDF ↗</a>{rules.blocks.map(b=><article key={b.title}><h3>{b.title}</h3>{b.paragraphs.map(p=><p key={p}>{p}</p>)}</article>)}<h3>All card designs & copy counts</h3><div className="rules-card-grid">{catalog.cards.map(c=><button key={c.key} onClick={()=>{setShowRules(false);setInspect(c.key);}}><img src={`/cards/${c.key}.png`} alt={c.name}/><span>{c.name} × {c.copies}</span></button>)}</div></section></div>}
 <footer className="online-footer"><span>UNICORN · Early playtest</span><button onClick={()=>setShowRules(true)}>Printed rules, unchanged</button>{table&&<button onClick={()=>refresh(room)}><RotateCcw size={13}/> Refresh connection</button>}</footer>
 </main>;
}
