'use client';
import { useEffect, useMemo, useState, type CSSProperties } from 'react';
import { flushSync } from 'react-dom';
import { ArrowUpRight, ArrowRight, Clock3, Users, Sparkles, FlaskConical, Gavel, Rocket, ShieldCheck, LockKeyhole, HandCoins, FileSignature, Megaphone, BrainCircuit, ShoppingBag, CreditCard, Dna, Eye, EyeOff, Swords, Repeat2, MessageCircle, RotateCcw, ChevronDown, BriefcaseBusiness, Handshake, Siren, Download, type LucideIcon } from 'lucide-react';
import catalog from '../game/cards.json';
import rules from '../game/rules.json';
import { cardInfo, freshTable, resolveDemo, scenarios, valueOf, type Scenario, type Stage } from '../game/demo';

const iconMap: Record<string, LucideIcon> = { FlaskConical, Gavel, Rocket, ShieldCheck, LockKeyhole, HandCoins, FileSignature, Megaphone, BrainCircuit, ShoppingBag, CreditCard, Dna, Handshake, Swords, Siren, Users };
const highlights = ['chief-scientist', 'viral-launch', 'poach', 'investor', 'founder-scandal', 'joint-venture', 'ditch', 'golden-handcuffs', 'patent-lawsuit', 'pr-crisis', 'fortune-500-contract', 'crisis-pr-team', 'cease-and-desist', 'founder-mixer'];
const downloadRoot = '/downloads/';

export default function Home() {
  return <>
    <header className="site-header wrap"><a className="brand" href="#" aria-label="UNICORN home"><Sparkles fill="currentColor"/> UNICORN<span>™</span></a><nav aria-label="Main navigation"><a href="#how-it-works">How to play</a><a href="#cards">The cards</a><a href="#playtest" className="nav-cta">Join the playtest <ArrowUpRight size={16}/></a></nav></header>
    <main>
      <section className="hero wrap">
        <div className="hero-copy"><div className="eyebrow"><span className="tiny-star">✳</span> BIG AMBITIONS. QUESTIONABLE FRIENDSHIPS.</div><h1>BUILD. RAISE.<br/>HIRE. <span>ATTACK.</span></h1><h2>First startup to <strong>$1B</strong> wins.</h2><p>Build the next big thing. Partner up. Ditch them.<br className="desktop-br"/> Try to stay friends after game night.</p><div className="hero-actions"><a href="#table" className="button lime">Try a table moment <ArrowUpRight size={20}/></a><a href="#how-it-works" className="text-button">See how it works <ArrowRight size={17}/></a></div><div className="game-meta"><span><Users size={17}/> 3–5 players</span><span><Clock3 size={17}/> ~45 min target</span><span>1 winner</span></div></div>
        <div className="hero-deck" aria-label="Startup cards surrounding the one billion dollar Unicorn card">
          <div className="orbit orbit-one"/><div className="orbit orbit-two"/>
          <div className="hero-card scientist"><div className="card-top">EMPLOYEE <FlaskConical size={16}/></div><h3>CHIEF<br/>SCIENTIST</h3><FlaskConical className="hero-icon" strokeWidth={1.1}/><div className="card-stat">+$125M<small>IN YOUR STARTUP</small></div></div>
          <div className="hero-card launch"><div className="card-top">PARTNERSHIP <Handshake size={16}/></div><h3>JOINT VENTURE</h3><Handshake className="hero-icon" strokeWidth={1.2}/><div className="card-stat">1 EACH<small>SHARE TWO EMPLOYEES</small></div></div>
          <div className="hero-card lawsuit"><div className="card-top">ATTACK <Gavel size={16}/></div><h3>PATENT<br/>LAWSUIT</h3><Gavel className="hero-icon" strokeWidth={1.3}/><div className="card-stat skip-stat">SKIP 1 TURN<small>OR BANK FOR +$10M</small></div></div>
          <div className="hero-card unicorn"><div className="card-top"><span>THE NEXT BIG THING</span><Sparkles size={16}/></div><div className="unicorn-milestone"><Sparkles className="milestone-spark" size={28} strokeWidth={1.4}/><div className="billion">$1B</div><div className="valuation-label">ONE BILLION. ONE WINNER.</div></div><div className="unicorn-footer"><div className="unicorn-title">UNICORN</div><div className="unicorn-caption">FIRST TO $1B WINS.</div></div></div>
          <div className="deck-sticker">FRIENDSHIP<br/>IS A LIABILITY.<span>↗</span></div><span className="deck-note">Together, until further notice.</span>
        </div>
      </section>
      <div className="ticker"><div>BUILD YOUR EMPIRE <Sparkles/> BETRAY YOUR COFOUNDER <Sparkles/> BECOME A UNICORN <Sparkles/> REQUEST A REMATCH <Sparkles/></div></div>
      <HowItWorks/><CardCollection/><GameDemo/><WhyPlay/><Startups/><PlaytestQuotes/><PlaytestForm/>
    </main>
    <footer className="footer wrap"><a className="brand" href="#"><Sparkles fill="currentColor"/> UNICORN<span>™</span></a><p>Big dreams. Small cards. Questionable ethics.</p><span>VALUATION-ONLY EDITION · 2026</span></footer>
  </>;
}
const steps = [
  {title:'Start a company',description:'Choose 1 of 3 startups. Start at $50M with 5 randomly dealt cards.',icon:BriefcaseBusiness},
  {title:'Draw one',description:'Take 1 card from the pile. If you’re over 7, discard down immediately.',icon:Repeat2},
  {title:'Play up to two',description:'Use a card’s effect, or bank it face-up for its valuation. Your choice.',icon:Rocket},
  {title:'Trust carefully',description:'Share employees with a partner. Keep a defense ready for Ditch.',icon:Handshake},
  {title:'Hit $1B',description:'Reach $1,000M at the end of your turn. Only you win—even if partnered.',icon:Sparkles},
];
function HowItWorks(){return <section id="how-it-works" className="section wrap how-section">
  <div className="section-heading"><div><div className="eyebrow">THE 60-SECOND PITCH</div><h2 className="section-title">One number to chase.<br/><span>Several friends to betray.</span></h2></div><p className="section-copy">Draw one. Play up to two.<br/>The rules are simple.<br/>The people at your table aren’t.</p></div>
  <div className="steps">{steps.map((s,i)=><div className="step" key={s.title}><div className="step-number">0{i+1}<s.icon size={24}/></div><h3>{s.title}</h3><p>{s.description}</p></div>)}</div>
  <div className="accounting valuation-only"><div className="accounting-intro"><span className="eyebrow">ONLY VALUATION MATTERS</span><h3>Your cards are your score.<br/>Your hand is your leverage.</h3><p>Lasting effects stay on the table, where everyone can count them.</p></div><div className="number-rule"><span>BUILD YOUR STARTUP</span><strong>+$125M</strong><p>Bank Chief Scientist face-up.<br/>Its valuation is now yours.</p></div><div className="number-rule tactic-rule"><span>OR KEEP YOUR OPTIONS</span><strong>+$10M</strong><p>Bank a defense for a small boost—or keep it hidden to save your company.</p></div></div>
  <details className="rules-details"><summary>The rest fits on a card. <span>Peek at the rules <ChevronDown size={18}/></span></summary><div className="rule-content"><div><h4>One card, one use</h4><p>Bank it for its printed valuation, or use its effect. A banked card cannot use its effect later. Used tactics do not also add their bank value.</p></div><div><h4>Keep the reactions ready</h4><p>Defenses come from your hand at the moment you’re attacked. They don’t use either of your two card plays. A partner may defend you, but never has to.</p></div><div><h4>A visible reminder</h4><p>PR Crisis stays beside a startup as a −$75M penalty. Patent Lawsuit stays until the next turn is skipped. Add visible values, subtract penalties, and keep building.</p></div></div><div className="rule-content rule-content-extra"><div><h4>Investor</h4><p>Give the other player the +$50M Investor card. Take one random card from their hidden hand. Not For Sale can stop the exchange.</p></div><div><h4>Joint Venture</h4><p>Both agree and commit one Employee each. Both count both Employees. One partner per player; your other cards and hand remain yours.</p></div><div><h4>Ditch</h4><p>The attacker takes both shared Employees. If blocked by Golden Handcuffs, the defender takes both instead. The winner of the exchange keeps their valuation; the loser drops. The venture ends.</p></div></div></details>
  <div className="downloads"><a href={downloadRoot+'UNICORN-founder-concept-one-page.pdf'} className="text-button" download><Download size={18}/> The game on one page</a><a href={downloadRoot+'UNICORN-printable-deck.pdf'} className="text-button" download><Download size={18}/> Full deck + complete rules</a></div>
</section>}
function CardCollection(){const cards=highlights.map(cardInfo);return <section id="cards" className="cards-section section"><div className="wrap"><div className="section-heading"><div><div className="eyebrow">SMALL CARDS. BIG CONSEQUENCES.</div><h2 className="section-title">Expose a secret.<br/><span>Ruin a perfectly good plan.</span></h2></div><p className="section-copy">Look at a rival’s hand. Steal a card.<br/>Make them miss a turn.<br/>Save your best defense for your partner.</p></div>
  <div className="card-legend" aria-label="Card categories">{[['Employees','cyan'],['Growth','lime'],['Funding','blue'],['Attack','coral'],['Defense','yellow'],['Investment / partnership','violet'],['Events','pink']].map(([label,color])=><span key={label}><i className={'swatch '+color}/>{label}</span>)}</div>
  <div className="card-grid" tabIndex={0} role="region" aria-label="Sample card collection, scroll to explore">{cards.map((card,i)=>{const Icon=iconMap[card.icon]||Sparkles;return <article className={'sample-card '+card.color+(card.outcome?' effect-card':'')} key={card.key} style={{'--tilt':`${(i%4-1.5)*1.3}deg`} as CSSProperties}>
    <div className="sample-top"><span>{card.category.toUpperCase()}</span><Icon size={17}/></div><h3>{card.name}</h3>
    {card.outcome?<div className="sample-art effect-art"><Icon strokeWidth={1.5}/><strong>{card.outcome.headline}</strong><span>{card.outcome.caption}</span></div>:<div className="sample-art"><Icon strokeWidth={1.25}/><span className="card-edition">{card.id}</span></div>}
    <p className="card-flavor">“{card.flavor}”</p><div className="card-use-label">{card.role==='asset'?'BUILD YOUR STARTUP':card.category==='Defense'?'YOUR DEFENSE':'PLAY THIS EFFECT'}</div><p className="card-effect">{card.effect}</p>
    {card.outcome?<div className="tactic-footer"><span>{card.id}</span><span>Bank instead: <b>+${card.value}M</b></span></div>:<><div className="sample-value"><strong>+${card.value}M</strong><span>VALUATION IN YOUR STARTUP</span></div><div className="card-visibility"><Eye size={14}/> Face-up asset</div></>}
  </article>})}</div>
  <p className="swipe-hint">Swipe to meet the rest of the deck <ArrowRight size={15}/></p><div className="exposure-rule"><div><Eye size={25}/><h3>Build in the open.</h3><p>Your startup’s cards are face-up. Bigger valuations give rivals something worth taking.</p></div><span className="versus">↔</span><div><EyeOff size={25}/><h3>Keep your intentions hidden.</h3><p>Your next card might save your partner. Or take both of your shared employees.</p></div></div></div></section>}

function GameDemo(){
  const [scenario,setScenario]=useState<Scenario>('ditch');
  const [stage,setStage]=useState<Stage>('ready');
  const [randomIndex,setRandomIndex]=useState(0);
  const setup=scenarios.find(s=>s.key===scenario)!;
  const before=useMemo(()=>freshTable(scenario),[scenario]);
  const state=useMemo(()=>resolveDemo(scenario,stage,randomIndex),[scenario,stage,randomIndex]);
  const actionCard=cardInfo(scenario);
  const pickScenario=(next:Scenario)=>{setScenario(next);setStage('ready');setRandomIndex(0)};
  const play=()=>{if(scenario==='investor')setRandomIndex(Math.floor(Math.random()*before.players[2].hand.length));setStage('played')};
  const messages:Record<Scenario,string>={
    poach:'Neural AI takes the Chief Scientist: +$125M for you, −$125M for Flash Commerce. The Poach card is discarded.',
    investor:`Flash Commerce gains $50M valuation. You receive ${cardInfo(state.players[0].hand.at(-1)!.key).name} from their shuffled, face-down hand.`,
    'founder-scandal':'Only you, playing Neural AI, see their hand. Their cards stay unchanged; Founder Scandal is discarded. Now you know what they’re hiding.',
    'joint-venture':'The CTO and Scientist are now shared. Neural AI gains access to the Scientist’s $125M; Flash Commerce gains the CTO’s $100M.',
    ditch:'Neural AI keeps both Employees and stays at $800M. Flash Commerce loses the shared $225M and falls to $675M. The venture ends.',
    'patent-lawsuit':stage==='skipped'?'Flash Commerce skips the whole turn: no draw and no card plays. The Lawsuit is discarded. They can react during other players’ turns.':'A Lawsuit now sits beside Flash Commerce. Their next turn will be skipped; their valuation is unchanged.',
    'cease-and-desist':'Viral Launch returns to Flash Commerce’s hand. They fall from $430M to $305M and can play the card again on their turn. The attack is discarded.',
    'founder-mixer':'Everyone passes one chosen card simultaneously. In this example, you pass Viral Launch to RocketWorks and receive PR Crisis from FinPay. Valuations stay the same.',
    'pr-crisis':'Flash Commerce drops by $75M. This penalty stays visible until Crisis PR Team removes it. The attack adds no valuation to Neural AI.',
  };
  const narration=stage==='ready'?setup.message:stage==='banked'?`You bank ${actionCard.name} for +$${actionCard.value}M. Its effect is unavailable, and nobody else is affected.`:stage==='blocked'?(scenario==='ditch'?'Flash Commerce reverses Ditch and takes both Employees. They stay at $900M; Neural AI falls to $575M. The venture ends.':`${cardInfo(setup.defense!).name} cancels the effect before it happens. Both played cards are discarded. Valuations stay unchanged.`):messages[scenario];
  useEffect(()=>{
    const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:unknown)=>void|Promise<void>}}).modelContext;
    if(!context?.registerTool)return;
    const life=new AbortController();
    try{Promise.resolve(context.registerTool({name:'set_unicorn_demo',title:'Try a UNICORN table moment',description:'Choose a scripted valuation-only example and its outcome. This changes only the visible demonstration, not a saved or multiplayer game.',inputSchema:{type:'object',properties:{scenario:{type:'string',enum:scenarios.map(s=>s.key)},stage:{type:'string',enum:['ready','played','blocked','banked','skipped']}},required:['scenario','stage'],additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:unknown)=>{
      if(!input||typeof input!=='object'||!('scenario' in input)||!('stage' in input))throw new Error('Choose a scenario and stage.');
      const chosen=scenarios.find(s=>s.key===input.scenario);if(!chosen||!['ready','played','blocked','banked','skipped'].includes(String(input.stage)))throw new Error('Unknown example or outcome.');
      const next=input.stage as Stage;if(next==='blocked'&&!chosen.defense||next==='skipped'&&chosen.key!=='patent-lawsuit')throw new Error('That outcome is not available for this example.');
      const result=resolveDemo(chosen.key,next,0);flushSync(()=>{setScenario(chosen.key);setStage(next);setRandomIndex(0)});document.getElementById('table')?.scrollIntoView({behavior:'smooth'});return {scenario:chosen.key,stage:next,valuations:result.players.map(p=>({name:p.name,value:valueOf(p,result.venture)}))};
    }},{signal:life.signal})).catch(()=>{});}catch{}return()=>life.abort();
  },[]);
  return <section id="table" className="section wrap table-section"><div className="section-heading"><div><div className="eyebrow">WELCOME TO THE TABLE</div><h2 className="section-title">Your partner has a plan.<br/><span>It might involve your exit.</span></h2></div><span className="demo-label">INTERACTIVE EXAMPLES</span></div>
    <div className="scenario-tabs" role="group" aria-label="Choose a card to try">{scenarios.map(s=><button type="button" key={s.key} aria-pressed={scenario===s.key} onClick={()=>pickScenario(s.key)}>{s.label}</button>)}</div>
    <div className={'game-table stage-'+stage}><div className="table-topline"><span><Users size={16}/> 4 STARTUPS. ONE WINNER.</span><span>YOU ARE NEURAL AI / <b>GOAL: $1,000M</b></span></div>
      <div className="companies">{state.players.map((company,i)=>{const total=valueOf(company,state.venture);const delta=total-valueOf(before.players[i],before.venture);const Icon=[BrainCircuit,Rocket,ShoppingBag,CreditCard][i];return <div key={company.id} className={'company '+company.color}><div className="company-heading"><div className="company-icon"><Icon size={23}/></div><span>{company.sector}</span></div><h3>{company.name}</h3><div className="company-value"><span className="valuation-number">${total}<small>M</small></span>{delta!==0&&<span className={'company-change '+(delta<0?'loss':'gain')}>{delta<0?'−':'+'}${Math.abs(delta)}M</span>}</div><div className="valuation-track"><span style={{width:Math.min(total/10,100)+'%'}}/></div><div className="company-asset">{company.cards.map(card=><span className="scientist-asset" key={card.id}>{cardInfo(card.key).name}<b>+${cardInfo(card.key).value}M</b></span>)}{company.penalties.map((p,k)=><span className="penalty-asset" key={k}>PR Crisis <b>−${Math.abs(p)}M</b></span>)}{company.skipNextTurn&&<span className="penalty-asset">Lawsuit: skip next turn</span>}{company.skipped&&<span className="penalty-asset">Turn skipped. Lawsuit discarded.</span>}{company.cards.length===0&&!company.penalties.length&&!company.skipNextTurn&&!company.skipped&&<span className="asset-placeholder">{state.venture&&(i===0||i===2)?'Your committed Employee is shared below.':'Other company cards remain in play.'}</span>}</div></div>})}</div>
      {state.venture&&<div className="venture-zone"><div><span className="eyebrow"><Handshake size={18}/> ACTIVE JOINT VENTURE</span><h3>Both startups count +$225M.</h3><p>One Employee each. One hidden reason to worry.</p></div><div className="shared-employees">{state.venture.employees.map(e=><div key={e.card.id}><span>COMMITTED BY {e.contributor==='neural'?'NEURAL AI':'FLASH COMMERCE'}</span><strong>{cardInfo(e.card.key).name}</strong><b>+${cardInfo(e.card.key).value}M</b></div>)}</div></div>}
      {(scenario==='founder-scandal'||scenario==='investor'||scenario==='cease-and-desist')&&<div className="demo-hand"><div><span className="eyebrow">{state.revealedTo?'YOUR PRIVATE VIEW':'FLASH COMMERCE’S HIDDEN HAND'}</span><p>{state.revealedTo?'Only the player using Founder Scandal sees these faces.':`${state.players[2].hand.length} cards. Their choices stay hidden.`}</p></div><div className="hand-cards">{state.players[2].hand.map((card,i)=><div key={card.id} className={state.revealedTo?'hand-face':'hand-back'}>{state.revealedTo?<><span>{cardInfo(card.key).category}</span><strong>{cardInfo(card.key).name}</strong></>:<><Sparkles size={22}/><span>HIDDEN {i+1}</span></>}</div>)}</div></div>}
      {scenario==='founder-mixer'&&<div className="venture-zone"><div><span className="eyebrow"><Users size={18}/> PASS LEFT AROUND THE TABLE</span><h3>Choose first. Pass together.</h3><p>Neural AI → RocketWorks → Flash Commerce → FinPay → Neural AI. Empty hands pass nothing.</p></div><div className="shared-employees">{state.players.map(p=><div key={p.id}><span>{p.name}</span><strong>{p.hand.length} hidden cards</strong><span>{stage==='played'?'Passed 1 · received 1':'Cards stay face-down'}</span></div>)}</div></div>}
      <div className="demo-action"><div className="played-icon">{stage==='blocked'?<ShieldCheck size={30}/>:scenario==='joint-venture'?<Handshake size={30}/>:<Swords size={30}/>}</div><div className="demo-narration"><span className="eyebrow">{stage==='ready'?'YOUR MOVE':stage==='banked'?'BANKED FOR VALUATION':stage==='blocked'?'DEFENSE PLAYED':actionCard.name.toUpperCase()}</span><p role="status" aria-live="polite">{narration}</p></div><div className="demo-controls">{stage==='ready'&&<><button type="button" className="button coral-button" onClick={play}>{setup.action}<ArrowUpRight size={18}/></button><button type="button" className="bank-button" onClick={()=>setStage('banked')}>Bank it instead: +${actionCard.value}M</button></>}{stage==='played'&&setup.defense&&<button type="button" className="button lime" onClick={()=>setStage('blocked')}>Try {cardInfo(setup.defense).name}<ShieldCheck size={18}/></button>}{stage==='played'&&scenario==='patent-lawsuit'&&<button type="button" className="bank-button" onClick={()=>setStage('skipped')}>Go to their next turn</button>}{stage!=='ready'&&<button type="button" className="reset-button" onClick={()=>setStage('ready')}><RotateCcw size={16}/> Reset this example</button>}</div></div>
    </div><p className="table-footnote">Scripted mid-game examples. Real hands are randomly dealt. <span>Valuation is the only score. Nobody is eliminated.</span></p>
  </section>;
}
function WhyPlay(){return <section className="why-section"><div className="wrap why-inner"><div><div className="eyebrow">A PERFECTLY REASONABLE REASON TO YELL</div><h2 className="section-title">Business is personal.<br/><span>Especially at this table.</span></h2><p className="section-copy">The best pitch doesn’t always win.<br/>The best-timed betrayal might.</p></div><div className="why-points"><div><MessageCircle/><div><h3>Read the room. Then bluff.</h3><p>Your partner might have Ditch. You might have Golden Handcuffs. Neither of you needs to admit it.</p></div></div><div><Swords/><div><h3>Attack the plan.</h3><p>Expose a hidden hand. Force a skipped turn. Take the card someone was counting on. Each attack changes a different decision.</p></div></div><div><Repeat2/><div><h3>Crashes make great comebacks.</h3><p>Lose a partnership, find a new one, and keep building. You’re still playing until someone reaches $1B.</p></div></div></div></div></section>}
function Startups(){const startups=catalog.cards.filter(c=>c.role==='startup');return <section className="section wrap startups-section"><div className="section-heading"><div><div className="eyebrow">CHOOSE YOUR PARTICULAR BRAND OF CHAOS</div><h2 className="section-title">Every empire starts small.<br/><span>Yours starts at $50M.</span></h2></div><p className="section-copy">Choose 1 of 3 randomly dealt startups.<br/>Same starting value. Same simple rules.<br/>Your cards decide what happens next.</p></div><div className="startup-grid">{startups.map(s=>{const Icon=iconMap[s.icon]||Sparkles;return <article key={s.key} className={'startup-card '+s.color}><span>STARTUP / {s.sector?.toUpperCase()}</span><Icon strokeWidth={1.2}/><h3>{s.name}</h3><p>{s.flavor}</p><strong className="startup-value">+$50M</strong></article>})}</div><p className="startup-note">Five cards in your opening hand. <span>Zero guarantees about who you can trust.</span></p>
  <details className="rules-details complete-rules"><summary>Settle the table debate. <span>Complete gameplay rules <ChevronDown size={18}/></span></summary><div className="full-rules-grid">{rules.blocks.map(b=><div key={b.title}><h4>{b.title}</h4>{b.paragraphs.map(p=><p key={p}>{p}</p>)}</div>)}</div></details>
  <div className="downloads"><a href={downloadRoot+'UNICORN-individual-cards.pdf'} className="text-button" download><Download size={18}/> Every card, one per page</a><a href={downloadRoot+'UNICORN-printable-deck.pdf'} className="text-button" download><Download size={18}/> 100-card deck + 20 startup / reference cards</a></div>
</section>}
function PlaytestQuotes(){return <section className="quotes-section"><div className="wrap"><div className="quote-label">OVERHEARD AT YOUR FUTURE GAME NIGHT <span>DEMO QUOTES · NOT REAL TESTIMONIALS</span></div><div className="quotes"><blockquote>“WE WERE<br/><em>PARTNERS.</em>”</blockquote><blockquote>“You tried to ditch me.<br/><em>I kept both employees.</em>”</blockquote><blockquote>“Again.”<span>THE INEVITABLE REMATCH.</span></blockquote></div></div></section>}
function PlaytestForm(){return <section id="playtest" className="section wrap playtest-section"><div className="playtest-copy"><span className="prototype-pill"><Sparkles size={14}/> EARLY PROTOTYPE. BIG POTENTIAL.</span><h2 className="section-title">Your friends.<br/>Your startup.<br/><span>Your villain era.</span></h2><p>We’re building UNICORN, and the first table<br className="desktop-br"/> could be yours. Get in early. Play a part.</p><div className="signup-aside"><Users size={20}/><span>Bring 2–4 friends.<br/><strong>Leave your business ethics at the door.</strong></span></div><p className="prototype-timing">About 45 minutes is the design target. This edition’s timing and balance still need live playtesting.</p></div><div className="signup-panel"><div className="signup-placeholder"><span className="eyebrow"><Sparkles size={14}/> KICKSTARTER LINK COMING SOON</span><h3>Join the first playtest</h3><p>We’re getting the campaign ready. The Kickstarter link will open here when it’s live.</p><button className="button lime submit-button" type="button" disabled title="Kickstarter link coming soon">Join the first playtest <ArrowUpRight size={20}/></button><p className="form-note">No signup is collected yet. Check back when the campaign launches.</p></div></div></section>}
