'use client';
import { useEffect, useState, type CSSProperties } from 'react';
import { flushSync } from 'react-dom';
import { ArrowUpRight, ArrowRight, Clock3, Users, Sparkles, FlaskConical, Gavel, Rocket, ShieldCheck, LockKeyhole, HandCoins, CircleSlash, FileSignature, Megaphone, BrainCircuit, ShoppingBag, CreditCard, Dna, Eye, EyeOff, MoveUpRight, Swords, Repeat2, MessageCircle, RotateCcw, Zap, ChevronDown, Landmark, BriefcaseBusiness } from 'lucide-react';

export default function Home() {
  return <>
    <header className="site-header wrap"><a className="brand" href="#" aria-label="UNICORN home"><Sparkles fill="currentColor"/> UNICORN<span>™</span></a><nav aria-label="Main navigation"><a href="#how-it-works">How to play</a><a href="#cards">The cards</a><a href="#playtest" className="nav-cta">Join the playtest <ArrowUpRight size={16}/></a></nav></header>
    <main>
      <section className="hero wrap">
        <div className="hero-copy"><div className="eyebrow"><span className="tiny-star">✳</span> BIG AMBITIONS. QUESTIONABLE FRIENDSHIPS.</div><h1>BUILD. RAISE.<br/>HIRE. <span>ATTACK.</span></h1><h2>First startup to <strong>$1B</strong> wins.</h2><p>Build the next big thing. Steal the best talent.<br className="desktop-br"/> Try to stay friends after game night.</p><div className="hero-actions"><a href="#table" className="button lime">Play UNICORN <ArrowUpRight size={20}/></a><a href="#how-it-works" className="text-button">See how it works <ArrowRight size={17}/></a></div><div className="game-meta"><span><Users size={17}/> 3–5 players</span><span><Clock3 size={17}/> ~45 minutes</span><span>∞ grudges</span></div></div>
        <div className="hero-deck" aria-label="Startup cards surrounding the one billion dollar Unicorn card">
          <div className="orbit orbit-one"/><div className="orbit orbit-two"/>
          <div className="hero-card scientist"><div className="card-top">EMPLOYEE <FlaskConical size={16}/></div><h3>CHIEF<br/>SCIENTIST</h3><FlaskConical className="hero-icon" strokeWidth={1.1}/><div className="card-stat">+$125M<small>VALUATION</small></div></div>
          <div className="hero-card launch"><div className="card-top">GROWTH <Rocket size={16}/></div><h3>VIRAL LAUNCH</h3><Rocket className="hero-icon" strokeWidth={1.2}/><div className="card-stat">+$125M</div></div>
          <div className="hero-card lawsuit"><div className="card-top">ATTACK <Gavel size={16}/></div><h3>PATENT<br/>LAWSUIT</h3><Gavel className="hero-icon" strokeWidth={1.3}/><div className="card-stat">−$100M<small>THEIR PROBLEM NOW.</small></div></div>
          <div className="hero-card unicorn"><div className="card-top"><span>THE NEXT BIG THING</span><Sparkles size={16}/></div><div className="unicorn-milestone"><Sparkles className="milestone-spark" size={28} strokeWidth={1.4}/><div className="billion">$1B</div><div className="valuation-label">ONE BILLION. ONE WINNER.</div></div><div className="unicorn-footer"><div className="unicorn-title">UNICORN</div><div className="unicorn-caption">FIRST TO $1B WINS.</div></div></div>
          <div className="deck-sticker">FRIENDSHIP<br/>IS A LIABILITY.<span>↗</span></div><span className="deck-note">Your next game night, funded.</span>
        </div>
      </section>
      <div className="ticker"><div>BUILD YOUR EMPIRE <Sparkles/> BETRAY YOUR COFOUNDER <Sparkles/> BECOME A UNICORN <Sparkles/> REQUEST A REMATCH <Sparkles/></div></div>
      <HowItWorks/>
      <CardCollection/>
      <GameDemo/>
      <WhyPlay/>
      <Startups/>
      <PlaytestQuotes/>
      <PlaytestForm/>
    </main>
    <footer className="footer wrap"><a className="brand" href="#"><Sparkles fill="currentColor"/> UNICORN<span>™</span></a><p>Big dreams. Small cards. Questionable ethics.</p><span>EARLY PROTOTYPE · 2026</span></footer>
  </>;
}

const steps = [
  {title:'Start a company',description:'Choose 1 of 3 randomly dealt startups. Try not to get attached.',icon:BriefcaseBusiness},
  {title:'Build your startup',description:'Hire people. Win customers. Raise money. Look very impressive.',icon:Rocket},
  {title:'Attack competitors',description:'Poach their employees. Sue them. Steal their customers.',icon:Swords},
  {title:'Defend yourself',description:'Lawyer up. Raise salaries. Keep a counter in your hand.',icon:ShieldCheck},
  {title:'Hit $1B',description:'Become the first Unicorn. Immediately demand a rematch.',icon:Sparkles},
];
function HowItWorks(){return <section id="how-it-works" className="section wrap how-section">
  <div className="section-heading"><div><div className="eyebrow">THE 60-SECOND PITCH</div><h2 className="section-title">A billion-dollar idea.<br/><span>A very bad group chat.</span></h2></div><p className="section-copy">You don’t need an MBA.<br/>You need a plan. And better lawyers<br className="desktop-br"/> than the person next to you.</p></div>
  <div className="steps">{steps.map((s,i)=><div className="step" key={s.title}><div className="step-number">0{i+1}<s.icon size={24}/></div><h3>{s.title}</h3><p>{s.description}</p></div>)}</div>
  <div className="accounting"><div className="accounting-intro"><span className="eyebrow">ONLY TWO NUMBERS MATTER</span><h3>Cards carry the accounting.<br/>You carry the strategy.</h3><p>If it lasts across turns, it’s a card on the table.</p></div><div className="number-rule cash-rule"><span>CASH</span><strong>$5M</strong><p>What you can spend.<br/>Some cards earn it. Others burn it.</p></div><div className="number-rule"><span>VALUATION</span><strong>$500M</strong><p>What your startup is worth.<br/>Add the visible cards. First to $1B wins.</p></div></div>
  <details className="rules-details"><summary>The rest fits on a card. <span>Peek at the rules <ChevronDown size={18}/></span></summary><div className="rule-content"><div><h4>Every turn, four simple steps</h4><ol><li>Resolve Cash effects.</li><li>Draw.</li><li>Play up to 2 actions.</li><li>Recalculate valuation.</li></ol></div><div><h4>Your startup, your hand</h4><p>Everyone begins with a startup, starting Cash, starting valuation, and a hidden hand. Choose 1 startup from 3 randomly dealt cards. The hand limit is approximately 7 cards.</p></div><div><h4>The table keeps things interesting</h4><p>Compete for 5 face-up market cards. Reveal a global event at the start of each round. Investments and lasting effects stay on the table as cards. Nobody is eliminated—startups can crash and recover.</p></div></div></details>
</section>}

const cards = [
  {name:'Chief Scientist',category:'Employee',color:'cyan',icon:FlaskConical,flavor:'Big brain. Bigger salary.',effect:'Cost: $3M · Cash each turn: −$1M',value:'+$125M',valueLabel:'VALUATION',visibility:'Face-up asset'},
  {name:'Viral Launch',category:'Growth',color:'lime',icon:Rocket,flavor:'The internet has entered the chat.',effect:'Your startup just went viral.',value:'+$125M',valueLabel:'VALUATION',visibility:'Face-up growth'},
  {name:'Patent Lawsuit',category:'Attack',color:'coral',icon:Gavel,flavor:'See you in court. Bring snacks.',effect:'Target startup loses $100M valuation while this card is active.',value:'−$100M',valueLabel:'TARGET VALUATION',visibility:'Hidden until played'},
  {name:'Golden Handcuffs',category:'Defense',color:'yellow',icon:LockKeyhole,flavor:'Sorry. They’re emotionally vested.',effect:'Cancel a Poach card.',value:'BLOCK',valueLabel:'POACH ATTACK',visibility:'Hidden reaction'},
  {name:'I Want In',category:'Investment',color:'violet',icon:HandCoins,flavor:'I believed in you. Five minutes ago.',effect:'Give a startup $5M Cash. Place this beside their company. If they later reach $500M, collect $15M from the bank.',value:'$5M → $15M',valueLabel:'CASH INVESTMENT → REWARD',visibility:'Stays beside their startup'},
  {name:'Not For Sale',category:'Defense',color:'yellow',icon:CircleSlash,flavor:'Respectfully, absolutely not.',effect:'Cancel an investment card.',value:'NO DEAL',valueLabel:'INVESTMENT CANCELLED',visibility:'Hidden reaction'},
  {name:'Fortune 500 Contract',category:'Growth',color:'lime',icon:FileSignature,flavor:'Yes, this could have been an email.',effect:'Cost: $1M · Cash each turn: +$2M',value:'+$100M',valueLabel:'VALUATION',visibility:'Face-up asset'},
  {name:'Founder Scandal',category:'Attack',color:'coral',icon:Megaphone,flavor:'Your pitch deck leaked. So did the group chat.',effect:'An attack card in development. Exact effect to be playtested.',value:'UH-OH.',valueLabel:'PROTOTYPE CARD',visibility:'Hidden until played'},
];
function CardCollection(){return <section id="cards" className="cards-section section"><div className="wrap"><div className="section-heading"><div><div className="eyebrow">SMALL CARDS. BIG CONSEQUENCES.</div><h2 className="section-title">Your unfair advantage.<br/><span>Until someone steals it.</span></h2></div><p className="section-copy">Good hires. Bad intentions.<br/>Meet a few cards that will make<br className="desktop-br"/> or break your company.</p></div>
<div className="card-legend" aria-label="Card categories">{[['Employees','cyan'],['Growth','lime'],['Funding','blue'],['Attack','coral'],['Defense','yellow'],['Investment','violet'],['Events','pink']].map(([label,color])=><span key={label}><i className={'swatch '+color}/>{label}</span>)}</div>
<div className="card-grid" tabIndex={0} role="region" aria-label="Sample card collection, scroll to explore">{cards.map((card,i)=><article className={'sample-card '+card.color} key={card.name} style={{'--tilt':`${(i%4-1.5)*1.3}deg`} as CSSProperties}><div className="sample-top"><span>{card.category.toUpperCase()}</span><card.icon size={17}/></div><h3>{card.name}</h3><div className="sample-art"><card.icon strokeWidth={1.25}/><span className="card-edition">U / {String(i+1).padStart(2,'0')}</span></div><p className="card-flavor">“{card.flavor}”</p><p className="card-effect">{card.effect}</p><div className="sample-value"><strong>{card.value}</strong><span>{card.valueLabel}</span></div><div className="card-visibility">{card.visibility.includes('Hidden')?<EyeOff size={13}/>:<Eye size={13}/>} {card.visibility}</div></article>)}</div>
<p className="swipe-hint">Swipe to meet the rest of the deck <ArrowRight size={15}/></p><div className="exposure-rule"><div><Eye size={25}/><h3>Build in the open.</h3><p>Your people, customers, and valuable assets go face-up. Everyone can see what’s worth stealing.</p></div><span className="versus">↔</span><div><EyeOff size={25}/><h3>Keep trouble in your hand.</h3><p>Attacks and counters stay hidden. That last card might be your best defense. Or a very good bluff.</p></div></div></div></section>}

type DemoStage = 'ready'|'poached'|'blocked'|'overridden';
function GameDemo(){const [stage,setStage]=useState<DemoStage>('ready');const stolen=stage==='poached'||stage==='overridden';const companies=[{name:'Neural AI',type:'AI',color:'violet',icon:BrainCircuit,value:stolen?600:725,initial:725},{name:'RocketWorks',type:'SPACE',color:'coral',icon:Rocket,value:550,initial:550},{name:'Flash Commerce',type:'CONSUMER',color:'lime',icon:ShoppingBag,value:stolen?555:430,initial:430},{name:'FinPay',type:'FINTECH',color:'cyan',icon:CreditCard,value:300,initial:300}];
const messages={ready:'Neural AI is getting dangerously close to $1B. Flash Commerce has other plans.',poached:'Flash Commerce poached the Chief Scientist. Neural AI loses $125M. Flash Commerce gains $125M.',blocked:'Golden Handcuffs cancels the poach. The scientist stays at Neural AI. Nice try, Flash Commerce.',overridden:'An Offer They Can’t Refuse ignores Golden Handcuffs. The scientist joins Flash Commerce after all.'};
useEffect(()=>{const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:unknown)=>void|Promise<void>}}).modelContext;if(!context?.registerTool)return;const life=new AbortController();try{Promise.resolve(context.registerTool({name:'set_unicorn_demo',title:'Try the UNICORN card interaction',description:'Set the visible sample game to the initial state, a poach, its defensive counter, or the counterattack. This is a demonstration, not a saved game.',inputSchema:{type:'object',properties:{stage:{type:'string',enum:['ready','poached','blocked','overridden']}},required:['stage'],additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:unknown)=>{if(!input||typeof input!=='object'||!('stage' in input)||!['ready','poached','blocked','overridden'].includes(String(input.stage)))throw new Error('Choose ready, poached, blocked, or overridden.');const next=input.stage as DemoStage;flushSync(()=>setStage(next));document.getElementById('table')?.scrollIntoView({behavior:'smooth'});return {stage:next,neuralAI:next==='poached'||next==='overridden'?600:725,flashCommerce:next==='poached'||next==='overridden'?555:430};}},{signal:life.signal})).catch(()=>{});}catch{}return()=>life.abort();},[]);
return <section id="table" className="section wrap table-section"><div className="section-heading"><div><div className="eyebrow">WELCOME TO THE TABLE</div><h2 className="section-title">Everything’s going great.<br/><span>Then your friend plays this.</span></h2></div><span className="demo-label">INTERACTIVE DEMO</span></div>
<div className={'game-table stage-'+stage}><div className="table-topline"><span><Users size={16}/> 4 STARTUPS. ONE UNICORN.</span><span>THE RACE TO <b>$1,000M</b></span></div><div className="companies">{companies.map((company,i)=><div key={company.name} className={'company '+company.color}><div className="company-heading"><div className="company-icon"><company.icon size={23}/></div><span>{company.type}</span>{i===0&&<span className="leader-tag">{stolen?'STILL IN IT':'IN THE LEAD'}</span>}</div><h3>{company.name}</h3><div className="company-value"><span className="valuation-number">${company.value}<small>M</small></span>{stolen&&(i===0||i===2)&&<span className={'company-change '+(i===0?'loss':'gain')}>{i===0?'−':'+'}$125M</span>}</div><div className="valuation-track"><span style={{width:company.value/10+'%'}}/></div><div className="company-asset">{(i===0&&!stolen||i===2&&stolen)?<span className="scientist-asset"><FlaskConical size={15}/> Chief Scientist <b>+$125M</b></span>:<span className="asset-placeholder">{i===0?'Scientist poached. Awkward.':i===2?'Your next hire is over there.':'Building the next big thing.'}</span>}</div></div>)}</div>
<div className="market"><div><span className="market-heading">SHARED MARKET</span><small>5 cards, face-up. First come, first hired.</small></div><div className="market-cards">{[{name:'Chief Scientist',icon:FlaskConical},{name:'Elite Engineer',icon:BrainCircuit},{name:'Growth Lead',icon:Megaphone},{name:'Government Grant',icon:Landmark},{name:'Fortune 500 Contract',icon:FileSignature}].map(c=><div key={c.name}><c.icon size={21}/><span>{c.name}</span></div>)}</div></div>
<div className="demo-action"><div className="played-icon">{stage==='blocked'?<LockKeyhole size={30}/>:<Swords size={30}/>}</div><div className="demo-narration"><span className="eyebrow">{stage==='ready'?'YOUR MOVE':stage==='blocked'?'REACTION: GOLDEN HANDCUFFS':stage==='overridden'?'COUNTER: OFFER THEY CAN’T REFUSE':'ATTACK: POACH KEY EMPLOYEE'}</span><p role="status" aria-live="polite">{messages[stage]}</p></div><div className="demo-controls">{stage==='ready'&&<button className="button coral-button" onClick={()=>setStage('poached')}>Poach their scientist <ArrowUpRight size={18}/></button>}{stage==='poached'&&<button className="button lime" onClick={()=>setStage('blocked')}>Play Golden Handcuffs <ShieldCheck size={18}/></button>}{stage==='blocked'&&<button className="button coral-button" onClick={()=>setStage('overridden')}>Offer They Can’t Refuse <ArrowUpRight size={18}/></button>}{stage==='overridden'&&<span className="table-verdict">“YOU TOOK MY SCIENTIST.”</span>}{stage!=='ready'&&<button className="reset-button" onClick={()=>setStage('ready')}><RotateCcw size={14}/> Reset the table</button>}</div></div></div>
<p className="table-footnote">No spreadsheet. No mystery math. Move the card, move the valuation. <span>Nobody’s out. The comeback is still on.</span></p></section>}

function WhyPlay(){return <section className="why-section"><div className="wrap why-inner"><div><div className="eyebrow">A PERFECTLY REASONABLE REASON TO YELL</div><h2 className="section-title">Business is personal.<br/><span>Especially at this table.</span></h2><p className="section-copy">The best pitch doesn’t always win.<br/>The best-timed betrayal might.</p></div><div className="why-points"><div><MessageCircle/><div><h3>Read the room. Then bluff.</h3><p>Negotiate, talk a big game, and make everyone wonder what’s in your hand. Lasting deals live on cards.</p></div></div><div><Swords/><div><h3>Pick your moment.</h3><p>Build quietly or sabotage loudly. Every face-up advantage gives your competitors a target.</p></div></div><div><Repeat2/><div><h3>Crashes make great comebacks.</h3><p>No early eliminations. Different startups, scarce market cards, and global events keep the rematches interesting.</p></div></div></div></div></section>}

function Startups(){return <section className="section wrap startups-section"><div className="section-heading"><div><div className="eyebrow">CHOOSE YOUR PARTICULAR BRAND OF CHAOS</div><h2 className="section-title">Every empire starts small.<br/><span>Yours starts with a card.</span></h2></div><p className="section-copy">Choose 1 of 3 randomly dealt startups.<br/>Same rules. A little different DNA.</p></div><div className="startup-grid">{[{type:'AI',name:'Neural AI',joke:'We put AI in it. Obviously.',color:'violet',icon:BrainCircuit},{type:'Consumer',name:'Flash Commerce',joke:'Everyone needs this. Probably.',color:'lime',icon:ShoppingBag},{type:'Fintech',name:'FinPay',joke:'Disrupting money. Running out of it.',color:'cyan',icon:CreditCard},{type:'Space',name:'RocketWorks',joke:'Our growth is literally vertical.',color:'coral',icon:Rocket},{type:'Biotech',name:'Biotech',joke:'One breakthrough away. Always.',color:'pink',icon:Dna}].map(s=><article key={s.type} className={'startup-card '+s.color}><span>STARTUP / {s.type.toUpperCase()}</span><s.icon strokeWidth={1.2}/><h3>{s.name}</h3><p>{s.joke}</p></article>)}</div><p className="startup-note">One strength. One weakness. One special ability. <span>The individual abilities are still being playtested.</span></p><div className="events-strip"><Zap size={25}/><div><h3>The market has mood swings, too.</h3><p>A global event at the start of each round affects everyone. Adapt accordingly.</p></div><div className="event-tags"><span>AI Boom</span><span>Funding Winter</span><span>Talent War</span></div></div></section>}

function PlaytestQuotes(){return <section className="quotes-section"><div className="wrap"><div className="quote-label">OVERHEARD AT YOUR FUTURE GAME NIGHT <span>DEMO QUOTES · NOT REAL TESTIMONIALS</span></div><div className="quotes"><blockquote>“YOU TOOK MY<br/><em>CHIEF SCIENTIST.</em>”</blockquote><blockquote>“I have never hated<br/>my friends <em>this much.</em>”</blockquote><blockquote>“Again.”<span>THE INEVITABLE REMATCH.</span></blockquote></div></div></section>}

function PlaytestForm(){return <section id="playtest" className="section wrap playtest-section"><div className="playtest-copy"><span className="prototype-pill"><Sparkles size={14}/> EARLY PROTOTYPE. BIG POTENTIAL.</span><h2 className="section-title">Your friends.<br/>Your startup.<br/><span>Your villain era.</span></h2><p>We’re building UNICORN, and the first table<br className="desktop-br"/> could be yours. Get in early. Play a part.</p><div className="signup-aside"><Users size={20}/><span>Bring 2–4 friends.<br/><strong>Leave your business ethics at the door.</strong></span></div></div><div className="signup-panel"><div className="signup-placeholder"><span className="eyebrow"><Sparkles size={14}/> KICKSTARTER LINK COMING SOON</span><h3>Join the first playtest</h3><p>We’re getting the campaign ready. The Kickstarter link will open here when it’s live.</p><button className="button lime submit-button" type="button" disabled title="Kickstarter link coming soon">Join the first playtest <ArrowUpRight size={20}/></button><p className="form-note">No signup is collected yet. Check back when the campaign launches.</p></div></div></section>}
